### ISSUE TITLE
Questions (custom php extension, nginx/apache) ?

### ISSUE THREAD

**Issue by khurshid-alam** [boekkooi/openshift-cartridge-php#21]
1. With no pear, how do I install custom extension (php-uuid, php-oauth) ? Usually I want to use these native extensions rather than some complicated library found in packagist.org. If I have the *.so files, can I make it work with this cartridge?
2. Do I have to use your [Nginx cartridge](https://github.com/boekkooi/openshift-cartridge-nginx) or does it work with any other existing app?
3. Any future plan to make it work with apache/httpd ?

**Comment by boekkooi** [comment]
Hi @khurshid-alam,
1. Please see https://github.com/boekkooi/openshift-cartridge-php#pecl
2. The PHP cartridge simply extends a primary/main cartridge so you can combine it in any way you wish. You are not forced to use the Nginx catridge.
3. Since php-fpm is provided by this cartridge it already work with [apache](https://wiki.apache.org/httpd/PHP-FPM) So no I have no plans to add anything extra for apache expect if someone submits a PR for the Readme or something.

I hope this answers you questions.

Cheers,
Warnar

**Comment by khurshid-alam** [comment]
@boekkooi Thanks. That helped.
